/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.company.panel;

import com.company.Context;
import com.company.dao.inter.EmpHistoryDaoInter;
import com.company.dao.inter.UserEmpHistoryDaoInter;
import com.company.entity.EmpHistory;
import com.company.entity.User;
import com.company.resume.Config;
import java.sql.Date;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author TURAL
 */
public class EmployeeHistoryPanel extends javax.swing.JPanel {

    /**
     * Creates new form EmployeeHistoryPanel
     */
    private EmpHistoryDaoInter empHistoryDao = Context.instanceEmpHistoryDao();
    private UserEmpHistoryDaoInter userEmpHistoryDao = Context.instanceUserEmpHistoryDao();

    public EmployeeHistoryPanel() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addEmpHistory = new javax.swing.JButton();
        updateEmpHistory = new javax.swing.JButton();
        deleteEmpHistory = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblEmpHistory = new javax.swing.JTable();

        addEmpHistory.setText("add");
        addEmpHistory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addEmpHistoryActionPerformed(evt);
            }
        });

        updateEmpHistory.setText("update");
        updateEmpHistory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateEmpHistoryActionPerformed(evt);
            }
        });

        deleteEmpHistory.setText("delete");
        deleteEmpHistory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteEmpHistoryActionPerformed(evt);
            }
        });

        tblEmpHistory.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(tblEmpHistory);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(addEmpHistory, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(updateEmpHistory, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(deleteEmpHistory, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addEmpHistory)
                    .addComponent(updateEmpHistory)
                    .addComponent(deleteEmpHistory))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void addEmpHistoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addEmpHistoryActionPerformed


    }//GEN-LAST:event_addEmpHistoryActionPerformed
    public void fillUserComponent() {
        DefaultTableModel tableModel = new DefaultTableModel();
        Vector vectorHeaders = new Vector();

        vectorHeaders.add("id");

        vectorHeaders.add("Header");
        vectorHeaders.add("Job Description");

        vectorHeaders.add("Begin Date");
        vectorHeaders.add("End Date");

        Vector vectorRows = new Vector();
        for (EmpHistory eh : userEmpHistoryDao.getAllEmpHistoryByUserId(Config.loggedInUser.getId())) {

            Vector row = new Vector();
            row.add(eh.getId());

            row.add(eh.getHeader());
            row.add(eh.getJobDescription());
            try {
                Date dt = eh.getBeginDate();
                String sdt = Config.sdf.format(dt);
                row.add(sdt);

            } catch (Exception ex) {
                row.add(null);

            }

            try {
                Date dt = eh.getEndDate();
                String sdt = Config.sdf.format(dt);
                row.add(sdt);

            } catch (Exception ex) {
                row.add(null);

            }
            vectorRows.add(row);
        }
        tableModel.setDataVector(vectorRows, vectorHeaders);
        tblEmpHistory.setModel(tableModel);

    }
    private void updateEmpHistoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateEmpHistoryActionPerformed
        int column = 0;

        int row = tblEmpHistory.getSelectedRow();
        System.out.println("Count : " + row);
        if (row > -1) {

        }
    }//GEN-LAST:event_updateEmpHistoryActionPerformed

    private void deleteEmpHistoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteEmpHistoryActionPerformed
        int column = 0;

        int row = tblEmpHistory.getSelectedRow();
        System.out.println("Count : " + row);
        if (row > -1) {

//            ((DefaultTableModel) tblEmpHistory.getModel()).removeRow(row);
//            listEmpHis.remove(row);
        }
    }//GEN-LAST:event_deleteEmpHistoryActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addEmpHistory;
    private javax.swing.JButton deleteEmpHistory;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable tblEmpHistory;
    private javax.swing.JButton updateEmpHistory;
    // End of variables declaration//GEN-END:variables

    public void fillUser(User usr) {

    }
}
