/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.company.panel;

import com.company.Context;
import com.company.dao.inter.SkillDaoInter;
import com.company.dao.inter.UserSkillDaoInter;
import com.company.entity.Skill;
import com.company.entity.User;
import com.company.entity.UserSkill;
import com.company.resume.Config;
import java.util.ArrayList;
import java.util.List;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author TURAL
 */
public class SkillPanel extends javax.swing.JPanel {

    private UserSkillDaoInter userSkillDao = Context.instanceUserSkillDao();
    private SkillDaoInter skillDao = Context.instanceSkillDao();
    private List<UserSkill> userSkillList = new ArrayList<UserSkill>();

    /**
     * Creates new form SkillPanel
     */
    public SkillPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAddSkill = new javax.swing.JButton();
        cbSkill = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblSkills = new javax.swing.JTable();
        btnDeleteSkill = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtSkillName = new javax.swing.JTextField();
        btnUpdateSkill = new javax.swing.JButton();
        sliderPower = new javax.swing.JSlider();

        btnAddSkill.setText("add");
        btnAddSkill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddSkillActionPerformed(evt);
            }
        });

        tblSkills.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tblSkills);

        btnDeleteSkill.setText("delete");
        btnDeleteSkill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteSkillActionPerformed(evt);
            }
        });

        jLabel1.setText("Skill");

        btnUpdateSkill.setText("save");
        btnUpdateSkill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateSkillActionPerformed(evt);
            }
        });

        sliderPower.setMaximum(10);
        sliderPower.setMinimum(1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbSkill, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtSkillName, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnUpdateSkill)
                        .addGap(37, 37, 37)
                        .addComponent(sliderPower, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnDeleteSkill)
                        .addGap(18, 18, 18)
                        .addComponent(btnAddSkill, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(54, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(cbSkill, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtSkillName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnUpdateSkill))
                    .addComponent(sliderPower, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDeleteSkill)
                    .addComponent(btnAddSkill))
                .addGap(34, 34, 34)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(13, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void fillWindow() {

        cbSkill.removeAllItems();

        for (Skill el : skillDao.getAll()) {
            cbSkill.addItem(el);
        }
        fillTable();
    }

    public void fillUserComponent() {
        fillWindow();

    }

    public void fillTable() {
        DefaultTableModel tableModel = new DefaultTableModel();
        Vector vectorHeaders = new Vector();

        vectorHeaders.add("Skill");
        vectorHeaders.add("Power");

        Vector vectorRows = new Vector();
        userSkillList = userSkillDao.getAllSkillByUserId(Config.loggedInUser.getId());
        for (UserSkill us : userSkillList) {
            Vector row = new Vector();

            row.add(us.getSkill().getName());
            row.add(us.getPower());
            vectorRows.add(row);
        }
        tableModel.setDataVector(vectorRows, vectorHeaders);
        tblSkills.setModel(tableModel);
    }

    private void btnAddSkillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddSkillActionPerformed
        String skillName = txtSkillName.getText();
        int skillPower = sliderPower.getValue();
        Skill skl = null;
        if (skillName != null && !skillName.trim().isEmpty()) {
            skl = new Skill(0, skillName);
            skillDao.insertSkill(skl);

        } else if (cbSkill.getSelectedItem() != null) {
            skl = (Skill) cbSkill.getSelectedItem();
            System.out.println(cbSkill.getSelectedItem());

        }
        userSkillDao.insertUserSkill(new UserSkill(0, Config.loggedInUser, skl, skillPower));
        fillTable();

    }//GEN-LAST:event_btnAddSkillActionPerformed

    private void btnDeleteSkillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteSkillActionPerformed
        int index = tblSkills.getSelectedRow();
        UserSkill usrSkill = userSkillList.get(index);
        userSkillDao.removeUserSkill(usrSkill.getId());
        fillTable();
    }//GEN-LAST:event_btnDeleteSkillActionPerformed

    private void btnUpdateSkillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateSkillActionPerformed
        int index = tblSkills.getSelectedRow();
        UserSkill usrSkill = userSkillList.get(index);

        String skillName = txtSkillName.getText();
        int skillPower = sliderPower.getValue();
        Skill skl = null;
        if (skillName != null && !skillName.trim().isEmpty()) {
            skl = new Skill(0, skillName);
            skillDao.insertSkill(skl);

        } else if (cbSkill.getSelectedItem() != null) {
            skl = (Skill) cbSkill.getSelectedItem();
            System.out.println(cbSkill.getSelectedItem());
        }

        usrSkill.setPower(skillPower);
        usrSkill.setSkill(skl);

        userSkillDao.updateUserSkill(usrSkill);
        fillTable();

    }//GEN-LAST:event_btnUpdateSkillActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddSkill;
    private javax.swing.JButton btnDeleteSkill;
    private javax.swing.JButton btnUpdateSkill;
    private javax.swing.JComboBox<Skill> cbSkill;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSlider sliderPower;
    private javax.swing.JTable tblSkills;
    private javax.swing.JTextField txtSkillName;
    // End of variables declaration//GEN-END:variables

    public void fillUser(User usr) {

    }
}
